before_script:
  - apt-get update
  - apt-get install -y git unzip
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php composer-setup.php
  - php -r "unlink('composer-setup.php');"

test:5:
  stage: test
  image: php:5
  script:
    - ./composer.phar install
    - ./composer.phar php5Test
  tags:
    - docker

test:7:
  stage: test
  image: php:7
  script:
    - ./composer.phar install
    - ./composer.phar test
  tags:
    - docker

